<?php
  // fail stojashih veshej
  $it['i.o.sta.bank'] = 'сундук|i.o.sta.bank|o|||||||||';
  $it['i.o.sta.cut_tree'] = 'пень|i.o.sta.cut_tree|o|||||||||';
  $it['i.o.sta.rock'] = 'камень|i.o.sta.rock|o|||||||||';
  $it['i.o.sta.arch_table'] = 'Столик Архимага|i.o.sta.arch_table|o|||||||||';
  $it['i.o.sta.clan_rock'] = 'Камень Клана|i.o.sta.clan_rock|o|||||||||';
  $it['i.o.sta.seashore'] = 'берег моря|i.o.sta.seashore|o|||||||||';
  $it['i.o.sta.riverbank'] = 'берег реки|i.o.sta.riverbank|o|||||||||';
  $it['i.o.sta.lake'] = 'берег озера|i.o.sta.lake|o|||||||||';
  $it['i.o.sta.ore'] = 'рудная жила|i.o.sta.ore|o|||||||||';
  $it['i.o.sta.portal'] = 'портал|i.o.sta.portal|o|||||||||';
  $it['i.o.sta.cutting'] = 'доска для шинковки|i.o.sta.cutting|o|||||||||';
  $it['i.o.sta.travnik'] = 'столик целителя|i.o.sta.travnik|o|||||||||';
  $it['i.o.sta.market'] = 'прилавки|i.o.sta.market|o|||||||||';
  $it['i.o.sta.nakovalqnja'] = 'наковальня|i.o.sta.nakovalqnja|o|||||||||';
  $it['i.o.sta.tree_bereza'] = 'береза|i.o.sta.tree_bereza|o|7||||||||';
  $it['i.o.sta.tree_elq'] = 'ель|i.o.sta.tree_elq|o|9||||||||';
  $it['i.o.sta.tree_jasenq'] = 'ясень|i.o.sta.tree_jasenq|o|8||||||||';
  $it['i.o.sta.tree_dub'] = 'дуб|i.o.sta.tree_dub|o|11||||||||';
  $it['i.o.sta.carpenter'] = 'стол плотника|i.o.sta.carpenter|o|||||||||';
  $it['i.o.sta.fireplace'] = 'кострище|i.o.sta.fireplace|o|off||#F8D545||||||'; // normal (yellow)
  $it['i.o.sta.fireplace2'] = 'кострище|i.o.sta.fireplace2|o|off||#BFFC49||||||'; // elven (green)
  $it['i.o.sta.fireplace3'] = 'кострище|i.o.sta.fireplace3|o|off||#49FCF6||||||'; // underground (blue)
  $it['i.o.sta.fireplace4'] = 'кострище|i.o.sta.fireplace4|o|off||#E32929||||||'; // orcish (red))
  $it['i.o.sta.telir_gate'] = 'ворота замка Телир|i.o.sta.telir_gate|o|||||||||';
  $it['i.o.sta.runestone_wellcome'] = 'рунный камень|i.o.sta.runestone_wellcome|o|||||||||';
  $it['i.o.sta.runestone_closelook'] = 'рунный камень|i.o.sta.runestone_closelook|o|||||||||';
  $it['i.o.sta.runestone_way'] = 'рунный камень|i.o.sta.runestone_way|o|||||||||';
  $it['i.o.sta.runestone_items'] = 'рунный камень|i.o.sta.runestone_items|o|||||||||';
  $it['i.o.sta.runestone_npc'] = 'рунный камень|i.o.sta.runestone_npc|o|||||||||';
  $it['i.o.sta.runestone_battle'] = 'рунный камень|i.o.sta.runestone_battle|o|||||||||';
  $it['i.o.sta.runestone_exp'] = 'рунный камень|i.o.sta.runestone_exp|o|||||||||';
  $it['i.o.sta.runestone_trade'] = 'рунный камень|i.o.sta.runestone_trade|o|||||||||';
  $it['i.o.sta.runestone_vk1'] = 'рунный камень|i.o.sta.runestone_vk1|o|||||||||';
  $it['i.o.sta.runestone_vk2'] = 'рунный камень|i.o.sta.runestone_vk2|o|||||||||';
  $it['i.o.sta.runestone_vk3'] = 'рунный камень|i.o.sta.runestone_vk3|o|||||||||';
  $it['i.o.sta.runestone_vk4'] = 'рунный камень|i.o.sta.runestone_vk4|o|||||||||';
  $it['i.o.sta.runestone_vk5'] = 'рунный камень|i.o.sta.runestone_vk5|o|||||||||'; // 6 net
  $it['i.o.sta.runestone_vk7'] = 'рунный камень|i.o.sta.runestone_vk7|o|||||||||';
  $it['i.o.sta.runestone_vk8'] = 'рунный камень|i.o.sta.runestone_vk8|o|||||||||';
  $it['i.o.sta.runestone_vk9'] = 'рунный камень|i.o.sta.runestone_vk9|o|||||||||';
  $it['i.o.sta.runestone_vk10'] = 'рунный камень|i.o.sta.runestone_vk10|o|||||||||';
  $it['i.o.sta.runestone_vk11'] = 'рунный камень|i.o.sta.runestone_vk11|o|||||||||';
  $it['i.o.sta.urna1'] = 'урна|i.o.sta.urna1|o|||||||||';
  $it['i.o.sta.juvtable'] = 'стол ювелира|i.o.sta.juvtable|o|||||||||';
  $it['i.o.sta.alchtable'] = 'стол алхимика|i.o.sta.alchtable|o|||||||||';
  $it['i.o.sta.yellowrock'] = 'желтый камень|i.o.sta.yellowrock|o|||||||||';
  $it['i.o.sta.venerarock'] = 'камень Венеры|i.o.sta.venerarock|o|||||||||';
  $it['i.o.sta.jupiterrock'] = 'камень Юпитера|i.o.sta.jupiterrock|o|||||||||';
  $it['i.o.sta.rosarock'] = 'камень росы|i.o.sta.rosarock|o|||||||||';
  $it['i.o.sta.merkurijrock'] = 'камень Меркурия|i.o.sta.merkurijrock|o|||||||||';
  $it['i.o.sta.fusionrock'] = 'камень Слития|i.o.sta.fusionrock|o|||||||||';
  $it['i.o.sta.lunarock'] = 'камень Луны|i.o.sta.lunarock|o|||||||||';
  $it['i.o.sta.saturnrock'] = 'камень Сатурна|i.o.sta.saturnrock|o|||||||||';
  $it['i.o.sta.marsrock'] = 'камень Марса|i.o.sta.marsrock|o|||||||||';
  $it['i.o.sta.dog_altar'] = 'Собачий Алтарь|i.o.sta.dog_altar|o|||||||||';
  $it['i.o.sta.weak_rock'] = 'слабая порода|i.o.sta.weak_rock|o|||||||||';
  $it['i.o.sta.tel2rele'] = 'портал Релен|i.o.sta.tel2rele|o|||||||||';
  $it['i.o.sta.xmas'] = 'Новогодняя Ёлка|i.o.sta.xmas|o|||||||||';
  $it['i.o.sta.furrer'] = 'стол скорняка|i.o.sta.furrer|o|||||||||';
?>